[정렬] 3월 8일
Altu-Bitu-2/Altu-Bitu-Study pull request #1
Opened 2022-03-08 08:08 UTC by soft-rain

#### 내용 & 질문
> 10804 11651에서 주소값을 써야하는 이유가 왜인지 궁금합니다! (주석에 작성해뒀습니다)

#### <기존 제출>
> 10804 12840 11651 1758 1431 1946 1026 

#### <추가 제출>
> X

2022-03-08 10:31 UTC, mkwkw requested changes
p2, p3 전체적으로 잘 풀어주셨습니다! 
1. 효율적인 코드를 위해 1758번에 comment 보시고 수정해보시길 바랍니다.
2.  전체적으로 주석이 많이 부족한 것 같아요. 어떻게 생각해서 이 코드를 작성하였는지 주석을 작성하시는 게 코드리뷰에도 좋고 나중에 유림님께서 코드 복기하실 때에도 좋을 것 같습니다!
3. 질문해주신 사항에 대해서 답변 드립니다. 
간단하게 말씀드리자면 매개 변수에 &를 달지 않고 매개변수를 그냥 넘기면 해당 함수에서 매개변수를 복사해서 사용하는데 큰 비용이 듭니다.(&안붙이고 매개변수 넘길 수 있습니다. 안 되는 건 아니에요!) 하지만 &로 넘기면 참조값만 사용하므로 상대적으로 비용이 덜 들어 효율적인 코드를 작성할 수 있습니다. https://boycoding.tistory.com/217 링크 참고하셔도 좋을 것 같아요.
4. 코드에 통일성이 있으면 좋을 것 같아요.(p3로만 표기하였습니다.) 내림차순 정렬할 때, rbegin, rend 그리고 greater 2가지로 써주셨는데 통일성이 있으면 좋을 것 같습니다.

2022-03-08 10:31 UTC, mkwkw commented on 1431.cpp
> +        }
p3. 이 조건문도 좋아요! 참고로 말씀드리자면 c++에는 isdigit()함수가 있어요. isdigit()의 괄호 안에 들어가는 인자가 숫자인지 아닌지 판별해주는 함수에요. 알아두시면 편리합니다!

2022-03-08 10:31 UTC, mkwkw commented on 1946.cpp
> +    int std = v[0].second;
p3. 5번째 줄에 std가 쓰여있습니다. c++내에 지정되어있는 것들의 이름과 같은 이름으로 변수를 선언해서 사용하는 것은 지양합니다. 간혹 오류가 발생할 수 있기 때문입니다.

2022-03-08 10:31 UTC, mkwkw commented on 1758.cpp
> +    }
p2. 이 for 문의 과정을 조금 더 빨리 끝낼 수 있는 방법이 있을 것 같아요!

2022-03-08 10:31 UTC, mkwkw commented on 1026.cpp
> +    sort(b.rbegin(), b.rend());
p3.

2022-03-08 10:31 UTC, mkwkw commented on 10804.cpp
> +    while (start < end || start == end) {
p2. 조건 하나로 할 수 있을 것 같아요!

2022-03-08 10:31 UTC, mkwkw commented on 11651.cpp
> +bool cmp(const pair<int, int> &a, pair<int, int> &b) {
p2. const 는 상수로 사용할 때 사용하는 표기입니다. 사용할 때 유의해주셔야합니다. 현재 첫 번째 매개변수에는 const가 있고 두 번째 매개변수에는 없는데 이 함수에서는 어떻게 작성하면 좋을까요?

2022-03-09 09:35 UTC, mkwkw commented
수정하시고 왼쪽 상단의 re-request review 버튼 눌러주세요!

2022-03-10 08:06 UTC, mkwkw commented
p2, p3만 있으므로 저 호출 안하시고 머지하셔도 됩니다!

2022-03-10 08:09 UTC, soft-rain commented
> p2, p3 전체적으로 잘 풀어주셨습니다!
> 
> 1. 효율적인 코드를 위해 1758번에 comment 보시고 수정해보시길 바랍니다.
> 2. 전체적으로 주석이 많이 부족한 것 같아요. 어떻게 생각해서 이 코드를 작성하였는지 주석을 작성하시는 게 코드리뷰에도 좋고 나중에 유림님께서 코드 복기하실 때에도 좋을 것 같습니다!
> 3. 질문해주신 사항에 대해서 답변 드립니다.
>    간단하게 말씀드리자면 매개 변수에 &를 달지 않고 매개변수를 그냥 넘기면 해당 함수에서 매개변수를 복사해서 사용하는데 큰 비용이 듭니다.(&안붙이고 매개변수 넘길 수 있습니다. 안 되는 건 아니에요!) 하지만 &로 넘기면 참조값만 사용하므로 상대적으로 비용이 덜 들어 효율적인 코드를 작성할 수 있습니다. https://boycoding.tistory.com/217 링크 참고하셔도 좋을 것 같아요.
> 4. 코드에 통일성이 있으면 좋을 것 같아요.(p3로만 표기하였습니다.) 내림차순 정렬할 때, rbegin, rend 그리고 greater 2가지로 써주셨는데 통일성이 있으면 좋을 것 같습니다.



> p2, p3만 있으므로 저 호출 안하시고 머지하셔도 됩니다!

네! 수정완료하여 커밋해두었고 머지하겠습니다~ 적어주신 내용 바탕으로 다음 과제때 잘 반영해보겠습니다! 감사해요 :)

2022-03-10 08:23 UTC, mkwkw requested changes
p2. 1758번에 수정이 필요합니다! 지금 코드는 이전 코드와 같아요. 제가 설명이 조금 부족했던 것 같아요.. 죄송합니다!

2022-03-10 08:23 UTC, mkwkw commented on 1758.cpp
> +    }
p2. 내림차순 정렬을 했으므로 앞 사람의 tip이 음수라면 다음 사람의 tip은 어떻게 될까요?

2022-03-10 08:29 UTC, soft-rain commented on 1758.cpp
> +    }
` sum += max(0, arr[i] - i);` 이렇게 if문 전체를 수정했는데, 이 외에도 다른 방법이 있을까요?

2022-03-10 10:05 UTC, mkwkw commented on 1758.cpp
> +    }
팁이 내림차순으로 정렬됩니다. 예를 들어, arr[0]<0이면, arr[0]>arr[1]이므로 arr[1]-1도 음수가 될 거에요. 그렇다면 팁이 양수일 때보다는 음수가 되었을 때를 검사하여 break를 하는 게 조금은 더 효율적인 방법일 것입니다!

2022-03-10 11:52 UTC, soft-rain commented on 1758.cpp
> +    }
> 팁이 내림차순으로 정렬됩니다. 예를 들어, arr[0]<0이면, arr[0]>arr[1]이므로 arr[1]-1도 음수가 될 거에요. 그렇다면 팁이 양수일 때보다는 음수가 되었을 때를 검사하여 break를 하는 게 조금은 더 효율적인 방법일 것입니다!

앗 어차피 정렬이 된 상태라 음수인 경우면 break해서 끊어주는게 더 효율적이네요.! 수정해서 커밋하고 머지하겠습니다 감사합니다!😆

2022-03-10 11:53 UTC, merged