[DFS&BFS] 4월 30일
Altu-Bitu-2/Altu-Bitu-Study pull request #14
Opened 2022-04-29 16:18 UTC by soft-rain

#### 내용 & 질문
> 11725에서 메모리 초과가 뜨는데, 범위 설정이 잘못된 건가요??

#### <기존 제출>
> 1697 2667 11725

#### <추가 제출>
>

2022-04-30 18:20 UTC, bsa0322 requested changes
p1. 유림님 안녕하세요! 😊 항상 열심히 해주셔서 저도 자극 받고 가는 것 같아요 !! 과제 하시느라 너무 수고하셨습니다! 😍 일단 전반적으로 너무 잘 풀어주셨어요! 라이브 코딩도 열심히 공부해 주신 것 같아서 뿌듯하네요!! 11725 메모리 초과도 금방 해결하실 수 있어요! 수정 후, 저 다시 리뷰어로 호출해주세요. 수고하셨습니다~! 🥰

2022-04-30 18:20 UTC, bsa0322 commented on Class13/11725.cpp
> +    v.assign(100001, vector<int> (10001, 0));
p1. c++에선 2차원 배열 사용 시 메모리가 1001 * 1001이 거의 맥시멈이예요! 이 부분에서 메모리초과가 나고 있어요. 인접 리스트를 사용해주시니, 열의 크기에서 메모리를 더 아낄 수 있어 보이네요! 😊 vector는 동적 할당이 가능하단 점이 큰 장점이죠!

2022-04-30 18:20 UTC, bsa0322 commented on Class13/11725.cpp
> +        }
p3. 위에서 continue로 끊어주었으니, if문에 해당했다면 어차피 해당 연산은 실행되지 않을 거예요! 그렇다면 현재 코드의 인덴테이션을 더 줄일 수 있어 보이네요!

2022-04-30 18:20 UTC, bsa0322 commented on Class13/1697.cpp
> +    visited[n] = true; //시작 지점 방문체크
p2. visited 배열을 활용하면 queue를 pair 쌍으로 관리하지 않고 해결할 수 있어요! 현재 다음 정점 탐색 시, 시간이 1씩 증가하게 돼죠. 그리고 방문 체크도 진행돼요. 그렇다면 둘을 합쳐 보면 어떨까요?

2022-05-01 09:58 UTC, soft-rain commented
수정 완료했습니다! 11725는 넘..이상하게 못찾았네요!!ㅋㅋ 11725번은 알려주신 방법이 훨씬 간편하다고 느꼈습니다..!!! 다른 것들은 추가제출로 주석 작성했습니다. 감사합니다🥰

2022-05-01 13:42 UTC, bsa0322 approved these changes
수정해주신 부분 모두 확인했습니다! 아주 좋아요~~! 인접 리스트의 초기화 부분 관련해서는 코멘트 더 참고해주셔도 좋을 것 같아요! 추가제출 3문제까지 모두 확인되셨습니다. 머지해주셔도 괜찮습니다~~! 수고하셨습니다! 🥰

2022-05-01 13:42 UTC, bsa0322 commented on Class13/11725.cpp
> +    v.assign(100001, vector<int>(2, 0));
좋아요~~! 트리의 특성을 살려서 지금처럼 열의 크기를 2로 고정해주신 것도 좋지만, 사실 인접리스트는 어차피 push_back으로 데이터를 저장하기 때문에 처음의 열 크기는 0으로 설정해주는 것이 좋습니다!! 😊

2022-05-01 13:50 UTC, soft-rain commented on Class13/11725.cpp
> +    v.assign(100001, vector<int>(2, 0));
앗 그걸 놓쳤네요! 다시 수정해서 푸시했습니다 감사합니다!!😆

2022-05-01 13:51 UTC, merged