[맵과셋] 3월 12일
Altu-Bitu-2/Altu-Bitu-Study pull request #3
Opened 2022-03-11 15:36 UTC by soft-rain

#### 내용 & 질문
> [2776] 시간 초과를 어떻게 해결해야할지 모르겠습니다!
> [19583] while 문 내에서 에러가 뜨는 것 같은데 수정을 어떻게 해야할 지 잘 모르겠습니다..!

#### <기존 제출>
> 2776 9375 11478 19583 20291 20920

#### <추가 제출>
> X

2022-03-13 04:40 UTC, hoit1302 requested changes
> [2776] 시간 초과를 어떻게 해결해야할지 모르겠습니다!
[19583] while 문 내에서 에러가 뜨는 것 같은데 수정을 어떻게 해야할 지 잘 모르겠습니다..!

궁금하신 부분은 아마 해결되었을 것 같습니다!!
현재 선택 6문제 중에 4문제 정답 확인 되셨습니다 ㅎㅎ
조금 더 힘내서 다 ac 받아봅시다 🚀 🔥 
좋은 하루 보내세요!

2022-03-13 04:40 UTC, hoit1302 commented on 03월 08일 - 맵과셋/20920.cpp
> +    }
p3. 사소한 의견
이렇게 구현하면서 더 잘 풀 수는 없을까? 한 번 쯤 의문을 가져보셨을 것 같아요.

튜터링 모범 코드에서는 입력받을 때 **단어가 중복되지 않도록 벡터에 string만을 저장하고** map에 단어 카운트 개수를 증가시켜요.
그리고 compare 함수에서는 map의 단어 카운트 개수에 접근하여 문자열을 문제 조건에 맞게 정렬시키고 있어요!
모범 코드가 오픈되면 꼭 확인해보세요 ☺️

2022-03-13 04:40 UTC, hoit1302 commented on 03월 08일 - 맵과셋/19583.cpp
> +    int quit_min = stoi(q.substr(3, 2));
p3. 사소한 의견
이 문제는 입력이 까다로워 보이지만, `22:00`를 통째로 입력받고 바로 문자열 대소 비교를 통해 쉽게 구현할 수 있답니다 👍🏻 
예를 들어 "22:00" < "22:05" -> true 를 반환합니다.

2022-03-13 04:40 UTC, hoit1302 commented on 03월 08일 - 맵과셋/19583.cpp
> +    freopen("input.txt", "r", stdin);
아시는 것 같지만 이 부분을 포함하고 있으면 제대로 채점이 불가합니다 :)

2022-03-13 04:40 UTC, hoit1302 commented on 03월 08일 - 맵과셋/19583.cpp
> +        cin >> time >> name;
p3. 사소한 의견
입력은 잘 받고 있습니다!!! 하지만 이렇게 더 쉽게 입력받을 수 있답니다!
```
while(cin >> time >> name) {

}
```

2022-03-13 04:40 UTC, hoit1302 commented on 03월 08일 - 맵과셋/19583.cpp
> +        }
p1. 꼭 반영해주세요!
이 부분은 사실 논리적 오류를 내포하고 있습니다!
문제를 꼼꼼히 읽고 다시 생각해봐주세요 🥰

2022-03-13 08:19 UTC, soft-rain commented on 03월 08일 - 맵과셋/20920.cpp
> +    }
벡터에 따로 단어만 string으로 저장하고, map에는 해당 단어의 카운트를 증가시킨 후 벡터 중복 제거한 뒤에 sort함수 이용해서 카운트를 비교하면 된다는 말씀이신가요? 중복 제거는 입력받을 때 바로 할 수 있는 방법은 없을까요??

2022-03-13 08:21 UTC, soft-rain commented
> > [2776] 시간 초과를 어떻게 해결해야할지 모르겠습니다!
> > [19583] while 문 내에서 에러가 뜨는 것 같은데 수정을 어떻게 해야할 지 잘 모르겠습니다..!
> 
> 궁금하신 부분은 아마 해결되었을 것 같습니다!! 현재 선택 6문제 중에 4문제 정답 확인 되셨습니다 ㅎㅎ 조금 더 힘내서 다 ac 받아봅시다 🚀 🔥
> 
> 참고로, 다시 코드 올려주신 뒤에 오른쪽 위에 reviewers 되돌이 표시 눌러주시면 제가 호출되어 재 리뷰가 가능합니다. 좋은 하루 보내세요!

20920 외에 모두 수정하여 다시 커밋했습니다! 코드 리뷰해주셔서 감사합니다😍

2022-03-14 02:23 UTC, hoit1302 commented on 03월 08일 - 맵과셋/20920.cpp
> +    }
A. 중복 제거를 입력받을 때 바로 할 수 있습니다!
입력 받을 때에 map에 저장하기 전에 이와 같이 작성하면 됩니다.
``` c++
        if (!words[word]) { 
            words.push_back(word);
        }
```

참고로, [] 연산자는 map에 없는 key를 참조하면 자동으로 선언된 값의 default 생성자를 호출해서 원소를 추가해줍니다. int를 선언했을 때에는 0 이란 값이 할당되고, c++에서는 0을 false 값으로 읽을 수 있기 때문에 위와 같이 작성할 수 있습니다!

2022-03-14 02:30 UTC, hoit1302 approved these changes
선택 6문제 중에 6문제 모두 제출 확인했습니다. 쿠폰도 하나 더 적립되셨습니다!!!
알고리즘에 대한 열정이 너무 뜨거워요! 🔥
제가 더 본받아야겠어요... 🥺
너무너무 수고하셨습니다! 좋은 하루 보내세요 💗

2022-03-14 02:30 UTC, hoit1302 commented on 03월 08일 - 맵과셋/2776.cpp
> +#include <unordered_map> //정렬되지 않은 컨테이너
이 문제는 unordered_set 컨테이너를 사용해도 AC 받을 수 있답니다!
너무너무 수고하셨습니다 👍🏻

2022-03-14 11:48 UTC, soft-rain commented on 03월 08일 - 맵과셋/2776.cpp
> +#include <unordered_map> //정렬되지 않은 컨테이너
감사합니다!! 😍

2022-03-14 11:48 UTC, merged