[스택,큐,덱] 03월 15일
Altu-Bitu-2/Altu-Bitu-Study pull request #4
Opened 2022-03-15 14:44 UTC by soft-rain

#### 내용 & 질문
> [1213] 홀수인 개수가 2개 이상일때는 처리를 했는데, 나머지로 문자 조합을 어떻게 작성해야할지 잘 모르겠습니다.
[2504] 소괄호 / 대괄호 각각은 계산했는데 서로 다른 종류의 괄호쌍이 붙어있거나, 내부에 있는 경우 계산을 어떻게 처리할지 잘 모르겠습니다..!
[2841] 로컬에서 돌리면 잘 나오는데 백준에서는 메모리 초과가 뜹니다!

#### <기존 제출>
> 1213, 2108, 2504, 11866, 2841

#### <추가 제출>
>

2022-03-16 13:08 UTC, hoit1302 requested changes
꾸준히 과제를 해내려고 노력하시는 모습 너무 멋져요!! 🥰 
지금 알고리즘 공부를 잘 해결해내고 있다고 전 확신하고 있어요!!! 🤗
적절하게 함수로 빼서 구현하고 수업에서 언급했던 내용들도 녹여있어서 감동했습니다 ㅎㅎ
알고리즘 문제들은 사실 손으로 많이 작성해보면 볼수록 실력이 쑥쑥 늘어요!

현재 선택 5문제 중에 1문제, 필수 2문제 중에 1문제 제출 확인했습니다.
p1으로 요청해드리면서 최대한 열심히 이해하실 수 있도록 적어보았습니다. 수정하고 다시 호출해주세요 !
질문도 너무너무 좋습니다 ㅎㅎ
화이팅입니다!!! ❤️‍🔥❤️‍🔥❤️‍🔥

2022-03-16 13:08 UTC, hoit1302 commented on Class3/2504.cpp
> +        }
p1. 꼭 반영해주세요

> [2504] 소괄호 / 대괄호 각각은 계산했는데 서로 다른 종류의 괄호쌍이 붙어있거나, 내부에 있는 경우 계산을 어떻게 처리할지 잘 모르겠습니다..!

A. 닫는 괄호가 나왔을 때, 
바로 직전의 괄호가 쌍이 맞는 여는 괄호라면 결과 값에 더해주고, 나눗셈으로 복원시켜주고, 해당 여는 괄호를 pop 해주어야 해요. → 잘 구현하셨습니다 🥳
바로 직전의 괄호가 쌍이 맞는 여는 괄호가 아니라면 결과 값에 더해주진 못하지만 깊이가 얕아지므로 _(첨부한 사진 참조)_ 나눗셈으로 복원시켜주고, 해당 여는 괄호를 pop 해주어야 해요!!
<br><br>
![IMG_BA566ABA7C1D-1](https://user-images.githubusercontent.com/68107000/158594909-ceeb9ea0-c532-4915-b952-d744634f9642.jpeg)

2022-03-17 16:21 UTC, soft-rain commented on Class3/2504.cpp
> +        }
수정 완료했습니다! 생각보다 고치는데 시간이 너무 오래걸려서 목요일 자정을 지났는데 코드리뷰X 마감일 지나고도 호출해도 되는걸까요?

2022-03-17 16:22 UTC, soft-rain commented
> 꾸준히 과제를 해내려고 노력하시는 모습 너무 멋져요!! 🥰 지금 알고리즘 공부를 잘 해결해내고 있다고 전 확신하고 있어요!!! 🤗 적절하게 함수로 빼서 구현하고 수업에서 언급했던 내용들도 녹여있어서 감동했습니다 ㅎㅎ 알고리즘 문제들은 사실 손으로 많이 작성해보면 볼수록 실력이 쑥쑥 늘어요!
> 
> 현재 선택 5문제 중에 1문제, 필수 2문제 중에 1문제 제출 확인했습니다. p1으로 요청해드리면서 최대한 열심히 이해하실 수 있도록 적어보았습니다. 수정하고 다시 호출해주세요 ! 질문도 너무너무 좋습니다 ㅎㅎ 화이팅입니다!!! ❤️‍🔥❤️‍🔥❤️‍🔥

수정 완료했습니다! 생각보다 고치는데 시간이 너무 오래걸려서 목요일 자정을 지났는데 코드리뷰X 마감일 지나고도 호출해도 되는걸까요?

2022-03-22 00:28 UTC, hoit1302 approved these changes
> 수정 완료했습니다! 생각보다 고치는데 시간이 너무 오래걸려서 목요일 자정을 지났는데 코드리뷰X 마감일 지나고도 호출해도 되는걸까요?
+) 요청 다시 드렸습니다! 항상 감사합니다~!!🤍

😭😭😭😭
제가 나중에 봐야지 하고 완전 까먹었네요 ㅠㅠ 죄송해요🥺 이럴 때 dm 보내주세요!!!
_답변은 저는 네라고 드리고 싶네여..ㅎㅎ 아마 다들 비슷할 거 같아요 워낙 열정 벗들이라...?_
최대한 코드리뷰 마감일까지 해주시면 좋겠지만 부득이하다면 하루 정도 지나서까지는 호출해주셔도 될 것 같습니다 ☺️
코드 수정 모두 확인했습니다!
선택 3문제, 구현 2문제 모두 제출 확인했습니다.
머지 해주셔도 됩니다!!!
너무 수고 많으셨습니다 ❤️

2022-03-22 02:53 UTC, soft-rain commented
> > 수정 완료했습니다! 생각보다 고치는데 시간이 너무 오래걸려서 목요일 자정을 지났는데 코드리뷰X 마감일 지나고도 호출해도 되는걸까요?
> > +) 요청 다시 드렸습니다! 항상 감사합니다~!!🤍
> 
> 😭😭😭😭 제가 나중에 봐야지 하고 완전 까먹었네요 ㅠㅠ 죄송해요🥺 이럴 때 dm 보내주세요!!! _답변은 저는 네라고 드리고 싶네여..ㅎㅎ 아마 다들 비슷할 거 같아요 워낙 열정 벗들이라...?_ 최대한 코드리뷰 마감일까지 해주시면 좋겠지만 부득이하다면 하루 정도 지나서까지는 호출해주셔도 될 것 같습니다 ☺️ 코드 수정 모두 확인했습니다! 선택 3문제, 구현 2문제 모두 제출 확인했습니다. 머지 해주셔도 됩니다!!! 너무 수고 많으셨습니다 ❤️

아니에요!! 항상 감사합니다!!😊🤍

2022-03-22 02:53 UTC, merged