[브루트 포스] 3월 22일
Altu-Bitu-2/Altu-Bitu-Study pull request #6
Opened 2022-03-22 08:07 UTC by soft-rain

#### 내용 & 질문
> [2503] 자리, 숫자 확인을 어떻게 해야할 지 아이디어가 잘 안떠올라요..! 힌트 같은게 더 있을까요?
[2798, 1018] clion에서 돌리면 잘 나오는데, 백준에서는 segfault nzec에러가 뜨는데, 리턴도 제대로 다 해놨는데 왜 이런 에러가 뜨는지 모르겠습니다.

#### <기존 제출>
> 10757 2503 2798 1018 1759 2858

#### <추가 제출>
>

2022-03-22 08:12 UTC, bsa0322 approved these changes
안녕하세요 😊 지금 정수론 과제는 있는데 브루트포스 과제 확인이 안되네요!! 확인 부탁드려요 🥰

2022-03-22 08:12 UTC, bsa0322 commented on Class4/10610.cpp
> +        cout << -1;
p2. 함수의 기능을 분리하기 위해 출력은 최대한 main()함수에서 처리해주시는 게 좋습니다~~!! 그리고 string 자체를 활용해서 더할 때만 정수형으로 바꿔주면 더 깔끔하게 리팩토링할 수 있을 것 같아요 😎

2022-03-22 08:59 UTC, soft-rain commented
> 안녕하세요 😊 지금 정수론 과제는 있는데 브루트포스 과제 확인이 안되네요!! 확인 부탁드려요 🥰

푸시하다가 오류가 났던 것 같아요! 정수론은 이미 머지했었는데 중간에 꼬인것 같아요!😅 다시 커밋했습니다~!!😊

2022-03-24 07:27 UTC, bsa0322 requested changes
p1. 리뷰가 너무 늦었네요!! 죄송합니다 ㅜㅜㅜ 😭😭 우선 전반적으로 깔끔하게 너무 잘 풀어주셨어요~! 함수화도 잘 해주셨구요! 너무 수고하셨습니다 🥰 런타임 에러가 난 부분에 대해서 아래에 코멘트 남겼어요. 앞으로 항상 주의해주셔야 해요!! 2503 관련 힌트도 더 남겨봤는데 혹시 부족하다면 언제든 저 불러주세요~! 
p1은 무조건 수정해주시고, p2가 붙은 코멘트는 수정해보시는 걸 추천드립니다!! 제가 리뷰가 늦기도 해서ㅜㅜ  오늘까지 맞았습니다 안 뜨셔도 넉넉히 기간 잡아 수정해서 맞으신 문제들 모두 과제 체크하도록 하겠습니다! 수정 후 저 다시 리뷰어로 호출해주세요~ ! 감사합니다 🥰

2022-03-24 07:27 UTC, bsa0322 commented on Class5/1018.cpp
> +    }
p1. 현재 런타임 에러가 나는 부분인데요! chess는 `string chess[50];` 으로 선언되었기에 아직 열에 대한 메모리는 만들어지지 않고 50개의 행에 대한 메모리만 만들어진 상태예요! 따라서 열까지 접근하는 chess[i][j]로 입력을 받으려 시도했기에 런타임 에러가 난 것입니다. 그럼 어떻게 수정할 수 있을까요? 고민해보시고 어렵다면 아래 힌트 참고해주세요

<details>
<summary>Hint</summary>
<div markdown="1">
&nbsp;&nbsp;&nbsp;&nbsp;
행에 대한 메모리만 만들어진 것이니, 행에 대한 입력을 한 번에 받으면 되겠네요!
</div>
</details>

2022-03-24 07:27 UTC, bsa0322 commented on Class5/17626.cpp
> +    for(int i=1, i<=)
아직 시도하고 계신 문제일까요? 힌트 필요하시면 말씀해주세요! 🥰

2022-03-24 07:27 UTC, bsa0322 commented on Class5/2503.cpp
> +    }
우선 입력으로 들어오는 질문에 대한 정보는 모두 저장해주시는 편이 좋아요! 해당 질문을 모두 만족하는 수를 찾아야 하니까요! 😎

2022-03-24 07:27 UTC, bsa0322 commented on Class5/2503.cpp
> +}
우선 정답이 될 수 있는 서로 다른 세 자리수는 123 ~ 987 까지 굉장히 적어요! 그리고 질문의 범위 n도 작죠! 그렇다면 질문으로 들어온 거에 맞는 정답을 찾으려하지 말고 반대로 생각해 볼까요? 정답이 될 수 있는 모든 수들을 검사하며 주어진 질문을 만족하는지 체크하는 거죠! 😉

여기까지 오셨다면, 해당 질문을 만족하는지는 string의 다양한 연산을 활용해서 쉽게 구현하실 수 있을 거예요! 여기서 막히신다면 아래 힌트 참고해주세요 ☺

<details>
<summary>Hint</summary>
<div markdown="1">
&nbsp;&nbsp;&nbsp;&nbsp;
먼저, 해당 위치에 수가 같은지 비교하는 스트라이크는 쉽게 구현하셨을 거예요. 그 후, 볼은 해당 경우가 아닌 것에서 그 수가 존재하는지만 더 비교해주면 되겠네요!
</div>
</details>

2022-03-24 07:27 UTC, bsa0322 commented on Class5/2798.cpp
> +    }
p1. 1018에서 런타임 에러가 난 이유와 동일한 이유예요 🥰 더불어 공백이 있으니 string으로 받으면 공백을 제거해줘야 해서 더 비효율적일 거예요. 기본적인 방법으로 입력을 받아볼까요?!

2022-03-24 07:27 UTC, bsa0322 commented on Class5/2798.cpp
> +    }
p2. 좋아요~~! 사실 미리 무엇을 해주면, 중간에 sum보다 커지는 경우를 거르면서` sum > answer` 연산 없이 바로 정답을 찾아줄 수 있어요! 수열에서 3개 수를 더하다가 sum보다 커지는 경우에서 자르려면, 그 후의 수들은 무조건 더 크다는 보장이 있어야 겠죠! 미리 무엇을 해줄 수 있을까요?

2022-03-24 07:27 UTC, bsa0322 commented on Class5/2858.cpp
> +    }
p1. 잘 풀어주셨지만, 해당 문제는 O(n)의 풀이로도 가능해요! 전체 타일의 개수를 사각형의 넓이로 생각해볼까요? 그렇담면 가로만 정해주어도 세로가 정해질 수 있겠죠! 😉

2022-03-24 12:28 UTC, soft-rain commented
> p1. 리뷰가 너무 늦었네요!! 죄송합니다 ㅜㅜㅜ 😭😭 우선 전반적으로 깔끔하게 너무 잘 풀어주셨어요~! 함수화도 잘 해주셨구요! 너무 수고하셨습니다 🥰 런타임 에러가 난 부분에 대해서 아래에 코멘트 남겼어요. 앞으로 항상 주의해주셔야 해요!! 2503 관련 힌트도 더 남겨봤는데 혹시 부족하다면 언제든 저 불러주세요~! p1은 무조건 수정해주시고, p2가 붙은 코멘트는 수정해보시는 걸 추천드립니다!! 제가 리뷰가 늦기도 했으니.. 꼭 오늘까지 맞았습니다 안 뜨셔도 넉넉히 기간 잡아 수정해서 맞으신 문제들 모두 과제 체크하도록 하겠습니다! 수정 후 저 다시 리뷰어로 호출해주세요~ ! 감사합니다 🥰

아니에요!! 피드백해주신 부분 거의 다 수정했는데, 2503번 문제만 결과값이 잘못 나와서 어디가 틀렸는지 궁금합니다!!(슬랙에도 질문 남겨두었어요!) 17626번은,,, 고민하다가 못 풀었는데 다른 힌트 또 받을 수 있을까요? 
추가로 체스판 문제에서 B/W로 시작하는걸 각각 ``black_board`` ``white_board``로 나눠서 하는건 됐는데, 이 둘을 어떻게 합쳐서 최솟값을 계산하면 좋을지는 해결을 못했어요..!! 방법이 있을까요?!?!
오늘도 좋은 리뷰 감사합니다!!😝

2022-03-27 07:11 UTC, bsa0322 approved these changes
수정해주신 거 모두 확인했습니다 ! 제가 말씀드린 것을 너무 잘 캐치해주셨어요! 수고하셨습니다 🥰 질문주신 부분에 대해서 코멘트 달아봤는데 너무 늦어서 이미 샘플코드 보셨을 수도 있겠네요 큐ㅠㅠ 참고해주시면 좋을 것 같아요! 😊

17626 힌트는 여기 남길께요!

우선 제곱수의 합은 최대 4개로 표현이 된다고 문제에 명시되어 있어요! 그렇다면 브루트 포스는 모든 경우의 수를 다 해보는 거라고 했으니.. 제곱수 1개부터 해당 수를 만드는 것이 가능한지 검사해주면 되는데요! 이때, 4까지 모두 다 하면 시간초과가 나요. 여기서 문제에서 제곱수의 합으로 표현이 가능하다 **증명했다** 했으니 만약 3개의 제곱수까지 검사했는데도 표현이 안됐다면, 정답 개수는 자연스레 무엇이 될까요?

힌트 더 필요하시면 말씀해주세요! 감사합니다! 수정하신다면 저 다시 불러주시고, 아니라면 머지해주셔도 괜찮습니다~! 

더불어 제가 늦게 확인한 만큼, 풀어주신 문제 모두 과제로 체크하겠습니다! 필수 2개, 선택 3개 우선 체크되셨습니다 😘

2022-03-27 07:21 UTC, soft-rain commented
> 수정해주신 거 모두 확인했습니다 ! 제가 말씀드린 것을 너무 잘 캐치해주셨어요! 수고하셨습니다 🥰 질문주신 부분에 대해서 코멘트 달아봤는데 너무 늦어서 이미 샘플코드 보셨을 수도 있겠네요 큐ㅠㅠ 참고해주시면 좋을 것 같아요! 😊
> 
> 17626 힌트는 여기 남길께요!
> 
> 우선 제곱수의 합은 최대 4개로 표현이 된다고 문제에 명시되어 있어요! 그렇다면 브루트 포스는 모든 경우의 수를 다 해보는 거라고 했으니.. 제곱수 1개부터 해당 수를 만드는 것이 가능한지 검사해주면 되는데요! 이때, 4까지 모두 다 하면 시간초과가 나요. 여기서 문제에서 제곱수의 합으로 표현이 가능하다 **증명했다** 했으니 만약 3개의 제곱수까지 검사했는데도 표현이 안됐다면, 정답 개수는 자연스레 무엇이 될까요?
> 
> 힌트 더 필요하시면 말씀해주세요! 감사합니다! 수정하신다면 저 다시 불러주시고, 아니라면 머지해주셔도 괜찮습니다~!
> 
> 더불어 제가 늦게 확인한 만큼, 풀어주신 문제 모두 과제로 체크하겠습니다! 필수 2개, 선택 3개 우선 체크되셨습니다 😘

우앗 감사합니다!!! 샘플코드랑 힌트 주신거 참고해서 다시 고민해볼게요! 감사합니다😍😍

2022-03-27 07:21 UTC, merged