[백트래킹] 3월 31일
Altu-Bitu-2/Altu-Bitu-Study pull request #8
Opened 2022-03-30 21:03 UTC by soft-rain

#### 내용 & 질문
> [20055] 답이 애매하게 다르게 나오는데 어디서 실수한 것인지 모르겠습니다..!!
[15663] sort를 기점으로 저장한 배열이 초기화가 되는데 왜인지 알 수 있을까요??
[10971] 이런 흐름이 맞는건지 궁금해요..! 

#### <기존 제출>
> 19071 20055 1205 15663

#### <추가 제출>
>

2022-03-30 21:05 UTC, soft-rain commented
제가 백트래킹을 완벽히 이해를 못한 것 같아서 코드가 너무 💩 그자체인데,,,😅 항상 감사합니다!!🥰

2022-03-31 08:21 UTC, mkwkw requested changes
백트래킹 과제 어려우셨을텐데 열심히 풀어주신 노력의 흔적이 보이네요!! 
질문 주신 사항과 코드에서 수정해야할 부분 코멘트 작성하였습니다:)
수정해보시고 저 다시 호출해주세요~

2022-03-31 08:21 UTC, mkwkw commented on Class7/20055.cpp
> +}
p1. 현재 코드에서 흐름은 첫 번째 test case를 예를 들자면, 벨트가 한 번 돌고, (로봇이 이동하고 - 첫 번째 단계에서는 로봇이 없습니다.), 로봇을 하나 올리고 step은 2가 되고 첫 번째 단계가 끝납니다.  다음 단계에서는 벨트가 한 번 돌고, 로봇이 이동해서 내구성 0인 칸이 하나 생기고 로봇을 내리고 로봇을 올리고 내구성이 0인 칸이 하나 더 생기고 step은 3이 되어 끝납니다. 그 다음에는 checkZero()에서 걸려서 while문이 break되고 step은 3으로 출력됩니다.
이렇게되어 step이 정답보다 1씩 더 크게 출력되는 상황입니다!
이 문제를 해결하려면 어떻게 해야할까요? 각 단계에서의 벨트와 로봇 deque의 상황을 출력해본다면 해결에 도움이 될 것 같아요:)

2022-04-01 06:08 UTC, soft-rain commented
#### 내용 & 질문
> [10971, 14888] 샘플코드 주석달아 추가제출합니다!

#### <기존 제출>
> 10971 20055 1205 15663

#### <추가 제출>
> 10971 14888

2022-04-01 07:23 UTC, mkwkw approved these changes
추가제출까지 합해서 필수 2문제, 선택 3문제 확인되었습니다!
백트래킹 적용하기 어려우셨을텐데 열심히 풀어주셔서 감사합니다~
백트래킹은 생각보다 지금처럼 사소한 오류가 나는 경우가 많아요.. 정말 꼼꼼하게 코드를 작성해야하는 알고리즘 중에 하나인 것 같습니다.
머지해주세요:)

2022-04-01 08:11 UTC, soft-rain commented
감사합니다!!🥰

2022-04-01 08:11 UTC, merged